### ISSUE TITLE
列表（段落）排版错误

### ISSUE THREAD

**Issue by justjavac** [barretlee/online-markdown#4]
当列表为段落时，CSS 排版错位

例如：

```
- Dictionary mode（字典模式）：字典模式也成为哈希表模式，V8 引擎使用哈希表来存储对象。

- Fast mode（快速模式）：快速模式使用类似 C 语言的 struct 来表示对象，如果你不知道什么是 struct，可以理解为是只有属性没有方法的 class。
```

排版为：

![image](https://cloud.githubusercontent.com/assets/359395/23093720/d03dae6c-f625-11e6-8913-62b35da42424.png)

------------------------

如果没有段落，则正常：

```
- 新建的对象是 fast 模式
- 添加太多的属性，变 slow
- 设置为其它对象的 prototype，变 fast
```

排版结果：

![image](https://cloud.githubusercontent.com/assets/359395/23093731/f5ef1c0e-f625-11e6-897b-34542ec0ad9c.png)

但是复制到微信公众号后，列表的文字颜色变成了默认黑色：

![image](https://cloud.githubusercontent.com/assets/359395/23093744/302d42d8-f626-11e6-9ed7-0b0a58f04a7b.png)

**Comment by barretlee** [comment]
稍后看看，尽快修复掉。
